### ISSUE TITLE
Error al tratar de enviar documento xml

### ISSUE THREAD

**Issue by sn94** [marcosjara/facturacionelectronicapy-setapi#9]
![WhatsApp Image 2023-12-08 at 10 28 05 AM](https://github.com/TIPS-SA/facturacionelectronicapy-setapi/assets/31597144/5426a5df-0c26-4bd3-91e1-570ad02d5075)

Es la primera vez que utilizo la libreria. Comprendo que es necesario un certificado pkcs12 para firmar el documento antes de enviarlo al SIFEN. La empresa para la cual estoy desarrollando aun no tramito la emision de su certificado, por lo cual, he generado uno yo misma para iniciar las pruebas. El error generado al intentar enviar el xml firmado se debe a que el cerfificado no es emitido por entidades autorizadas? aun cuando estoy el parametro "env" es test?
Esto es parte del  codigo que utilizo:

```
let cert_path = '/Users/soniatoledo/Desktop/agua_vista_sap_node/certs/aguapkcs12.pfx';
let env = 'test'
let key = 'aguavista';
let id = 1;
let result = await setApi.default
            .recibe(id, xmlSigned, env, cert_path, key);
```

**Comment by otte845** [comment]
Aun para operar en el ambiente de pruebas necesitas el certificado digital válido, pero el error que te debería de salir dice explícitamente eso.

Ese error es cuando la SET tiene problemas, pasa muchísimo con el servidor de pruebas.

Te recomiendo que hagas una llamada "segura" (una vez que tengas el certificado) como consultar tu propio ruc y así saber si el servidor esta funcionando o no

**Comment by sn94** [comment]
Comprendo, gracias por la aclaracion, lo tendre en cuenta.
